const menu = [
  {
    id: 1,
    title: 'Apple',
    category: 'weed',
    price: 15.99,
    img: "https://th.bing.com/th/id/OIP.cuKCrchtpgCNMFuYEwMmigHaF5?pid=ImgDet&rs=1",
    desc: ` An Apple is a juicy and edible fruit of the apple tree, scientifically called the Malus Domestica. It has its roots in Central Asia and now spread to many countries that cultivate many varieties of apples`,
  },
  {
    id: 2,
    title: 'Banana',
    category: 'fruits',
    price: 13.99,
    img: 'https://thumbs.dreamstime.com/b/bananas-isolated-white-background-picture-high-quality-clipping-path-62232367.jpg',
    desc: `Banana is a tropical fruit, renowned for its nutritional goodness. It belongs to the Musaceae family and is botanically a berry, due to multiple seeds inside it.`,
  },
  {
    id: 3,
    title: 'Mango',
    category: 'weed',
    price: 6.99,
    img: 'https://th.bing.com/th/id/OIP.46X7YPInhUBs6hRy9qfF8QHaFG?pid=ImgDet&rs=1',
    desc: `Mango, the “King of the fruits” is a drupe fruit that grows in tropical regions. It has yellow colored tangy pulp, with a unique flavor and fragrance`,
  },
  {
    id: 4,
    title: 'Orange',
    category: 'veggies',
    price: 20.99,
    img: 'https://th.bing.com/th/id/OIP.r_vW_e2PfIZzeWNsFWW4awHaFQ?pid=ImgDet&rs=1',
    desc: `Orange is a citrus fruit that is loaded with nutrients like Vitamin C. They are round in shape, with a greenish to orange color leathery, outer skin`,
  },
  {
    id: 5,
    title: 'Papaya',
    category: 'fruits',
    price: 22.99,
    img: 'https://th.bing.com/th/id/OIP.sARClBD3_D_AdqAlHxXfsQHaE1?pid=ImgDet&rs=1',
    desc: `Papaya is another tropical fruit that is native to Mexico and Central America. The scientific name of Papaya is Carica Papaya and is also called Paw Paw.`,
  },
  {
    id: 6,
    title: 'Watermelon',
    category: 'veggies',
    price: 18.99,
    img: 'https://image.freepik.com/free-photo/watermelon-isolated-white-background_88281-3976.jpg',
    desc: `Watermelon is a popular summer fruit that can now enjoyed throughout the year, thanks to hybridization. It belongs to the family of Cucurbitaceae and grows on a vine`,
  },
  {
    id: 7,
    title: 'Kiwi',
    category: 'weed',
    price: 8.99,
    img: 'https://i.pinimg.com/originals/00/78/64/0078646b3415a351d5b0847d6291a523.jpg',
    desc: `Kiwi, also called the Chinese Gooseberry is originally from the Newzealand. It belongs to the family of Actinidiaceae and has a fuzzy, brown outer cover that resembles the brown feathers of a Kiwi bird`,
  },
  {
    id: 8,
    title: 'Grapes',
    category: 'fruits',
    price: 12.99,
    img: 'https://static.vecteezy.com/system/resources/previews/001/223/778/large_2x/grapes-isolated-on-white-background-free-photo.jpg',
    desc: `Grapes are one of the most widely grown types of fruits in the world, chiefly for the making of different wines. They belong to the vitaceae and known to be one of the oldest cultivated plants in the history of mankind. `,
  },
   {
    id: 9,
    title: 'Guava',
    category: 'fruits',
    price: 12.99,
    img: 'https://th.bing.com/th/id/R.ca5409b4865c82aa054510b980b65e64?rik=x%2bUi4oMmwx3ckA&riu=http%3a%2f%2ffb48495671d2d91cd8e6-fcdd7c10a736b671537f0d814c4bbb93.r71.cf1.rackcdn.com%2f9600.jpg&ehk=09vEA6GybB2toYmtMvmBLjxBW3EcF2DrEaN71ZEWpAU%3d&risl=&pid=ImgRaw&r=0',
    desc: `Guava is a tropical variety of fruit that is native to Mexico, Central America and other warm countries. The common guava grows on a small tree that belongs to the Myrtaceae family and has either pink or white-coloured flesh.`,
  },
  {
    id: 10,
    title: 'Pineapple',
    category: 'veggies',
    price: 12.99,
    img: 'https://d2gg9evh47fn9z.cloudfront.net/800px_COLOURBOX1493602.jpg',
    desc: `Pineapple is another popular type of fruit grown is many tropical countries and is originally from South America. Each pineapple is grown from many unpollinated flowers of the plant, making it a multiple fruit.`,
  },
  {
    id: 11,
    title: 'Strawberry',
    category: 'fruits',
    price: 12.99,
    img: 'https://th.bing.com/th/id/OIP.dABFcZZ215atBx80jWWNAAHaGH?pid=ImgDet&rs=1',
    desc: `Strawberry is a luscious, red fruit grown on plants belonging to the Rose or Rosaceae family. Technically, strawberry is not a berry, as the seeds are grown on the outside and don’t come from a single ovary.`,
  },
  {
    id: 12,
    title: 'Plum',
    category: 'fruits',
    price: 12.99,
    img: 'https://th.bing.com/th/id/OIP.3b5J8sb42pktOWj-edto-QHaGe?pid=ImgDet&rs=1',
    desc: `Plums are drupe or stone fruits that belong to the Prunus genus. There are almost 40 kinds of fruits in this variety, but the popular ones are – the red and the deep purple plums, which have sweet and juicy flesh inside. `,
  },
  {
    id: 13,
    title: 'Pear',
    category: 'fruits',
    price: 12.99,
    img: 'https://th.bing.com/th/id/OIP.ohdFXJCYjk-ZR2RsJ8lCEAHaF2?pid=ImgDet&rs=1',
    desc: `A pear is another sweet-tasting fruit that comes from the family of Rosaceae. It is also one of the oldest cultivated types of fruits in the world and is considered to be the “gift from the Gods” by the ancient Greeks.`,
  },
  {
    id: 14,
    title: 'Melon',
    category: 'fruits',
    price: 12.99,
    img: 'https://th.bing.com/th/id/OIP.xo8c4ivBvJcQDlMTWMq5HgHaGV?pid=ImgDet&rs=1',
    desc: `The word Melon refers to many kinds of fruits that belong to the Cucurbitaceae family. There are more than 30 different types of melons cultivated in different parts of the world and vary in size, texture, color, shape and flavour profile.`,
  },
  {
    id: 15,
    title: 'Lychee',
    category: 'fruits',
    price: 12.99,
    img: 'https://image.freepik.com/free-photo/lychee-white-background-tropical-fruit_253984-4044.jpg',
    desc: `Lychee or Litchi belongs to the soapberry family and is the only member in the Litchi genus. It is an aromatic fruit variety that grows in clusters of 2 to 30 numbers in each.`,
  },
  {
    id: 16,
    title: 'Jackfruit',
    category: 'fruits',
    price: 12.99,
    img: 'https://thumbs.dreamstime.com/b/ripe-jackfruit-isolated-white-background-ripe-half-jackfruit-isolated-white-background-172042794.jpg',
    desc: `Jackfruit is one of the largest varieties of fruits in the world and is grown in tropical countries like India. An average jackfruit can reach upto 2 feet in length and 15-18kgs in weight. `,
  },
  {
    id: 17,
    title: 'Grapefruit',
    category: 'fruits',
    price: 12.99,
    img: 'https://th.bing.com/th/id/OIP.TMHvK_NO27cb23zERL7xdwHaEq?pid=ImgDet&rs=1',
    desc: `A Grapefruit is a tropical fruit that belongs to the citrus varieties of fruits like orange and lime. It is a round, medium-sized fruit that contains reddish-pink pulp, which can taste anywhere between bitter, sour or mildly sweet. `,
  },
  {
    id: 18,
    title: 'Cherry',
    category: 'fruits',
    price: 12.99,
    img: 'https://thumbs.dreamstime.com/b/cherries-collection-cherry-isolated-white-background-113444444.jpg',
    desc: `Cherry is a drupe fruit that belongs to the family of prunus fruit varieties. There are two major types of Cherries cultivated commercially – The sour cherries and the sweet cherries. `,
  },
 
 
];
export default menu;